name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: peaceiris/actions-gh-pages@v3
    - name: Use Node.js ${{ matrix.node-version }}
      with:
        publish_dir: ./app/dist
    - run: cd app
    - run: npm install
    - run: npm run build --if-present
