name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian-latest

    strategy:
      matrix:
        node-version: 18.x
    steps:
    - uses: peaceiris/actions-gh-pages@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        publish_dir: ./app/dist
    - run: cd app
    - run: npm install
    - run: npm run build --if-present
